// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.degiere.message.domain;

import net.degiere.message.domain.Message;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Message_Roo_Configurable {
    
    declare @type: Message: @Configurable;
    
}
